### ISSUE TITLE
Disable Wayland Session in Post-Install System Config

### ISSUE THREAD

**Issue by andrejd1** [xerolinux/xero-welcome-desktop#2]
I tried to **Enable Wayland Session** tweak in the **Post-Install System Config**, but it broke x11. Now, when I try to switch back to x11, every system utilities (settings, konsole, dolphin, ...) crashes.

Can you make an option to **Disable Wayland Session** to revert this?

![image](https://user-images.githubusercontent.com/9055381/226099570-87ffe0c7-12e0-4079-8144-6187f12da350.png)

**Comment by TechXero** [comment]
Wrong tool ...

But I will consider it for this one.. Why not ? I warned time and time again against Wayland but no one listens, it's like am talking to the wall .. But one way to learn I guess, and that's by trying and suffering it wrath.. You could have just logged in to X11 from login screen top left drop down..
